//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IDuplexSrv", CallbackContract=typeof(WFClient.ServiceReference1.IDuplexSrvCallback))]
    public interface IDuplexSrv {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDuplexSrv/Login", ReplyAction="http://tempuri.org/IDuplexSrv/LoginResponse")]
        void Login(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDuplexSrv/Login", ReplyAction="http://tempuri.org/IDuplexSrv/LoginResponse")]
        System.Threading.Tasks.Task LoginAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDuplexSrv/SendText", ReplyAction="http://tempuri.org/IDuplexSrv/SendTextResponse")]
        void SendText(string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDuplexSrv/SendText", ReplyAction="http://tempuri.org/IDuplexSrv/SendTextResponse")]
        System.Threading.Tasks.Task SendTextAsync(string text);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDuplexSrv/Logout", ReplyAction="http://tempuri.org/IDuplexSrv/LogoutResponse")]
        void Logout(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDuplexSrv/Logout", ReplyAction="http://tempuri.org/IDuplexSrv/LogoutResponse")]
        System.Threading.Tasks.Task LogoutAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDuplexSrvCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDuplexSrv/TextForUsers")]
        void TextForUsers(string text);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDuplexSrvChannel : WFClient.ServiceReference1.IDuplexSrv, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DuplexSrvClient : System.ServiceModel.DuplexClientBase<WFClient.ServiceReference1.IDuplexSrv>, WFClient.ServiceReference1.IDuplexSrv {
        
        public DuplexSrvClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public DuplexSrvClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public DuplexSrvClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public DuplexSrvClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public DuplexSrvClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Login(string name) {
            base.Channel.Login(name);
        }
        
        public System.Threading.Tasks.Task LoginAsync(string name) {
            return base.Channel.LoginAsync(name);
        }
        
        public void SendText(string text) {
            base.Channel.SendText(text);
        }
        
        public System.Threading.Tasks.Task SendTextAsync(string text) {
            return base.Channel.SendTextAsync(text);
        }
        
        public void Logout(string name) {
            base.Channel.Logout(name);
        }
        
        public System.Threading.Tasks.Task LogoutAsync(string name) {
            return base.Channel.LogoutAsync(name);
        }
    }
}
